=== GitTooth/JD2017-02-20/src/by/it/sorokoee/jd02_09/Person.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://jd02_09.sorokoee.it.by"
        xmlns:tns="http://jd02_09.sorokoee.it.by"
        elementFormDefault="qualified">
<element name="Persons">
<complexType>
    <sequence>
        <element name="Person"
                 type="tns:Person"
                 maxOccurs="unbounded">
        </element>
    </sequence>
</complexType>
</element>

<complexType name="Person">
<sequence>
    <element name="Email" type="string"/>
    <element name="Nicname" type="string"/>
    <element name="Password" type="string"/>
    <element name="Ads" type="tns:Ads"/>
</sequence>
</complexType>

<complexType name="Ads">
<sequence>
    <element name="Ad" type="tns:Ad"
             minOccurs="1"
             maxOccurs="unbounded"/>
</sequence>
</complexType>

<complexType name="Ad">
<all>
    <element name="Car" type="string"/>
    <element name="YearOfIssue" type="integer"/>
    <element name="TypeEngine" type="string"/>
    <element name="CapacityEngine" type="double"/>
    <element name="Spares" type="string"/>
</all>
</complexType>



</schema>

=== GitTooth/JD2017-02-20/src/by/it/sorokoee/jd02_09/Persons+xsd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Persons xmlns="http://jd02_09.sorokoee.it.by"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://jd02_09.sorokoee.it.by Person.xsd">
    <Person>
        <Email>sor@gmail.com</Email>
        <Nicname>sor</Nicname>
        <Password>qwerty</Password>
        <Ads>
            <Ad>
                <Car>BMW 5(E60)</Car>
                <YearOfIssue> 2005 </YearOfIssue>
                <TypeEngine>дизель</TypeEngine>
                <CapacityEngine>2.0</CapacityEngine>
                <Spares>двигатель, бампер</Spares>
            </Ad>
            <Ad>
                <Car>BMW 7(E65)</Car>
                <YearOfIssue> 2007 </YearOfIssue>
                <TypeEngine>дизель</TypeEngine>
                <CapacityEngine>3.0</CapacityEngine>
                <Spares>двигатель, кузов</Spares>
            </Ad>
        </Ads>
    </Person>

</Persons>

=== GitTooth/JD2017-02-20/src/by/it/sorokoee/jd02_07/Persons+xsd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Persons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://sorokoee.it-academy/xml/Persons Person.xsd"
xmlns="http://sorokoee.it-academy/xml/Persons">
    <Person>
        <Email>sor@gmail.com</Email>
        <Nicname>sor</Nicname>
        <Password>qwerty</Password>
        <Ads>
            <Ad>
                <Car>BMW 5(E60)</Car>
                <YearOfIssue> 2005 </YearOfIssue>
                <TypeEngine>дизель</TypeEngine>
                <CapacityEngine>2.0</CapacityEngine>
                <Spares>двигатель, бампер</Spares>
            </Ad>
            <Ad>
                <Car>BMW 7(E65)</Car>
                <YearOfIssue> 2007 </YearOfIssue>
                <TypeEngine>дизель</TypeEngine>
                <CapacityEngine>3.0</CapacityEngine>
                <Spares>двигатель, кузов</Spares>
            </Ad>
        </Ads>
    </Person>

</Persons>
