=== GitTooth/JD2017-02-20/src/by/it/smirnov/jd02_08/BankLimits.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://it-academy.by/xml/BankLimits"
        xmlns:tns="http://it-academy.by/xml/BankLimits"
        elementFormDefault="qualified">

    <element name="BankLimits">
        <complexType>
            <sequence>
                <element name="Banks"
                         type="tns:Banks"
                         maxOccurs="unbounded">
                </element>
                <element name="Limits"
                         type="tns:Limits"
                         maxOccurs="unbounded">
                </element>
            </sequence>
        </complexType>
    </element>

    <complexType name="Banks">
        <sequence>
            <element name="Bank"
                     type="tns:Bank"
                     maxOccurs="unbounded">
            </element>
        </sequence>
    </complexType>

    <complexType name="Bank">
        <sequence>
            <element name="Name" type="string"/>
            <element name="MFO" type="integer"/>
            <element name="FullMFO" type="string"/>
            <element name="Address" type="tns:Address"/>
            <element name="Group" type="string" minOccurs="0" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="Address">
        <sequence>
            <element name="Country" type="string"/>
            <element name="City" type="string"/>
            <element name="Street" type="string"/>
            <element name="Number" type="string"/>
            <element name="PostIndex" type="string" minOccurs="0" maxOccurs="unbounded"/>
        </sequence>
    </complexType>


    <complexType name="Limits">
        <sequence>
            <element name="Limit"
                     type="tns:Limit"
                     maxOccurs="unbounded">
            </element>
        </sequence>
    </complexType>

    <complexType name="Limit">
        <sequence>
            <element name="Lim" type="tns:Lim" maxOccurs="unbounded"/>
        </sequence>
        <attribute name="group" type="string" use="required" />
    </complexType>

    <complexType name="Lim">
        <sequence>
            <element name="Opers" type="tns:Opers"/>
        </sequence>
        <attribute name="fromDate" type="date" use="required" />
    </complexType>

    <complexType name="Opers">
        <sequence>
            <element name="Oper"
                     type="tns:Oper"
                     maxOccurs="unbounded">
            </element>
        </sequence>
    </complexType>

    <complexType name="Oper">
        <sequence>
            <element name="Summa" type="float"/>
            <element name="Valut" type="string"/>
        </sequence>
        <attribute name="type" type="tns:TypeOper" use="required" />
    </complexType>

    <simpleType name="TypeOper">
        <restriction base="string">
            <enumeration value="MM"/>
            <enumeration value="FX"/>
        </restriction>
    </simpleType>

</schema>

=== GitTooth/JD2017-02-20/src/by/it/smirnov/jd02_07/XSD/BankLimits.xml
<?xml version="1.0" encoding="utf-8" ?>
<BankLimits xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://it-academy.by/xml/BankLimits BankLimits.xsd"
            xmlns="http://it-academy.by/xml/BankLimits">
    <Banks>
        <Bank>
            <Name>АСБ "Беларусбанк"</Name>
            <MFO>333</MFO>
            <FullMFO>124589333</FullMFO>
            <Address>
                <Country>Беларусь</Country>
                <City>Минск</City>
                <Street>пр.Дзержинского</Street>
                <Number>23</Number>
            </Address>
            <Group>Первая группа</Group>
        </Bank>
        <Bank>
            <Name>ОАО "Приорбанк"</Name>
            <MFO>749</MFO>
            <FullMFO>124589479</FullMFO>
            <Address>
                <Country>Беларусь</Country>
                <City>Минск</City>
                <Street>ул.В.Хоружей</Street>
                <Number>10</Number>
                <PostIndex>220088</PostIndex>
            </Address>
            <Group>Вторая группа</Group>
        </Bank>
    </Banks>
    <Limits>
        <Limit group="Первая группа">
            <Lim fromDate="2017-01-01">
                <Opers>
                    <Oper type="MM">
                        <Summa>1000.00</Summa>
                        <Valut>USD</Valut>
                    </Oper>
                    <Oper type="FX">
                        <Summa>2000.00</Summa>
                        <Valut>EUR</Valut>
                    </Oper>
                </Opers>
            </Lim>
            <Lim fromDate="2017-02-01">
                <Opers>
                    <Oper type="MM">
                        <Summa>1500.00</Summa>
                        <Valut>USD</Valut>
                    </Oper>
                    <Oper type="FX">
                        <Summa>2500.00</Summa>
                        <Valut>EUR</Valut>
                    </Oper>
                </Opers>
            </Lim>
        </Limit>
        <Limit group="Вторая группа">
            <Lim fromDate="2017-01-01">
                <Opers>
                    <Oper type="MM">
                        <Summa>5000.00</Summa>
                        <Valut>USD</Valut>
                    </Oper>
                    <Oper type="FX">
                        <Summa>7000.00</Summa>
                        <Valut>EUR</Valut>
                    </Oper>
                </Opers>
            </Lim>
            <Lim fromDate="2017-02-01">
                <Opers>
                    <Oper type="MM">
                        <Summa>4500.00</Summa>
                        <Valut>USD</Valut>
                    </Oper>
                    <Oper type="FX">
                        <Summa>8500.00</Summa>
                        <Valut>EUR</Valut>
                    </Oper>
                </Opers>
            </Lim>
        </Limit>
    </Limits>
</BankLimits>
