=== GitTooth/JD2017-02-20/src/by/it/prigozhanov/jd02_07/CarRental.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://fastcarrental.ru/xml/CarRental"
        xmlns:tns="http://fastcarrental.ru/xml/CarRental"
        elementFormDefault="qualified">

    <element name="CarList">
        <complexType>
            <sequence>
                <element name="SportCars"
                         type="tns:SportCars"
                         maxOccurs="1"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="SportCars">
         <sequence>
             <element name="Car"
                      type="tns:Car"
                      maxOccurs="unbounded"/>
         </sequence>
    </complexType>

    <complexType name="Car">
        <all>
             <element name="Discription"/>
            <element name="Model" type="tns:Model"/>
            <element name="Price" type="string"/>
            <element name="Location" type="string"/>
        </all>
    </complexType>

    <complexType name="Model">
        <sequence>
            <element name="Name" type="string"/>
            <element name="HP" type="positiveInteger"/>
            <element name="FuelConsumption" type="positiveInteger"/>
            <element name="Seats" type="positiveInteger"/>
            <element name="Doors" type="positiveInteger"/>
            <element name="LuggageCapacity" type="positiveInteger"/>
        </sequence>
    </complexType>



</schema>

=== GitTooth/JD2017-02-20/src/by/it/prigozhanov/jd02_07/CarRental.xml
<?xml version="1.0" encoding="utf-8" ?>
<CarList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://fastcarrental.ru/xml/CarRental CarRental.xsd"
         xmlns="http://fastcarrental.ru/xml/CarRental">

    <SportCars>
        <Car>
            <Discription>A fearless design philosophy has led to the DB11's iconic looks</Discription>
            <Model>
                <Name>Aston Martin DB11</Name>
                <HP>620</HP>
                <FuelConsumption>20</FuelConsumption>
                <Seats>4</Seats>
                <Doors>2</Doors>
                <LuggageCapacity>3</LuggageCapacity>
            </Model>
            <Price>1420</Price>
            <Location>Minsk</Location>
        </Car>
        <Car>
            <Discription>Meet the AMG model of the new Mercedes-Benz S-Class Coupe.</Discription>
            <Model>
                <Name>Mercedes-Benz S63</Name>
                <HP>600</HP>
                <FuelConsumption>15</FuelConsumption>
                <Seats>4</Seats>
                <Doors>2</Doors>
                <LuggageCapacity>2</LuggageCapacity>
            </Model>
            <Price>1240</Price>
            <Location>Moscow</Location>
        </Car>
        <Car>
            <Discription>Improved styling of the second-generation 2017 Porsche Panamera</Discription>
            <Model>
                <Name>Porsche Panamera</Name>
                <HP>520</HP>
                <FuelConsumption>13</FuelConsumption>
                <Seats>4</Seats>
                <Doors>4</Doors>
                <LuggageCapacity>4</LuggageCapacity>
            </Model>
            <Price>1000</Price>
            <Location>Berlin</Location>
        </Car>
    </SportCars>
</CarList>
