=== GitTooth/JD2017-02-20/src/by/it/loktev/jd02_09a/group.xsd
<?xml version="1.0" encoding="utf-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://jd02_09a.loktev.it.by"
        xmlns:tns="http://jd02_09a.loktev.it.by"
        elementFormDefault="qualified">

<element name="group">
    <complexType>
    <choice maxOccurs="unbounded" minOccurs="0">
        <element name="square" type="tns:TSquare" />
        <element name="circle" type="tns:TCircle" />
        <element name="text" type="tns:TText" />
    </choice>
    </complexType>
</element>

<complexType name="TCircle">
    <attribute name="centerx" type="integer" use="required"></attribute>
    <attribute name="centery" type="integer" use="required"></attribute>
    <attribute name="radius" type="integer" use="required"></attribute>
    <attribute name="fill" type="string"></attribute>
    <attribute name="stroke" type="string"></attribute>
</complexType>

<complexType name="TSquare">
    <attribute name="left" type="integer" use="required"></attribute>
    <attribute name="top" type="integer" use="required"></attribute>
    <attribute name="width" type="integer" use="required"></attribute>
    <attribute name="height" type="integer" use="required"></attribute>
    <attribute name="fill" type="string"></attribute>
    <attribute name="stroke" type="string"></attribute>
</complexType>

<complexType name="TText">
    <simpleContent>
        <extension base="string">
            <attribute name="left" type="integer"></attribute>
            <attribute name="top" type="integer"></attribute>
        </extension>
    </simpleContent>
</complexType>


</schema>

=== GitTooth/JD2017-02-20/src/by/it/loktev/jd02_09a/group.xml
<?xml version="1.0" encoding="utf-8" ?>
<group xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://jd02_09a.loktev.it.by group.xsd"
         xmlns="http://jd02_09a.loktev.it.by"
>
    <square left="20" top="30" width="40" height="5" stroke="blue" />
    <square left="20" top="30" width="40" height="5" stroke="blue" />
    <circle centerx="50" centery="50" radius="20" fill="red" />
    <text left="77" top="88">
        HELLO!
    </text>
    <circle centerx="50" centery="50" radius="20" fill="red" />
    <square left="20" top="30" width="40" height="5" stroke="blue" />
    <circle centerx="50" centery="50" radius="20" fill="red" />
</group>
