=== GitTooth/JD2017-02-20/src/by/it/zeynalov/jd02_07/HomeWork/CoffeeHouse.dtd
<!ELEMENT CoffeeHouses (CoffeeHouse)+>
<!ELEMENT CoffeeHouse (Administrator, Waitress, Barista, Menus)>
<!ELEMENT Administrator (#PCDATA)>
<!ELEMENT Waitress (#PCDATA)>
<!ELEMENT Barista (#PCDATA)>
<!ELEMENT Menus (Menu)+>
<!ELEMENT Menu (Description, Latte, Americano, Cappuccino, Espresso)>
<!ELEMENT Description (#PCDATA)>
<!ELEMENT Latte (#PCDATA)>
<!ELEMENT Americano (#PCDATA)>
<!ELEMENT Cappuccino (#PCDATA)>
<!ELEMENT Espresso (#PCDATA)>

=== GitTooth/JD2017-02-20/src/by/it/zeynalov/jd02_07/HomeWork/CoffeeHouses+DTD.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE CoffeeHouses SYSTEM "CoffeeHouse.dtd">
<CoffeeHouses>
    <CoffeeHouse>
        <Administrator>Sam</Administrator>
        <Waitress>Kira</Waitress>
        <Barista>Din</Barista>
        <Menus>
            <Menu>
                <Description>Menu</Description>
                <Latte>Latte</Latte>
                <Americano>Americano</Americano>
                <Cappuccino>Cappuccino</Cappuccino>
                <Espresso>Espresso</Espresso>
            </Menu>
        </Menus>
    </CoffeeHouse>
</CoffeeHouses>
