=== GitTooth/JD2017-02-20/src/by/it/zeynalov/jd02_07/HomeWork/CoffeeHouse.xsd
<?xml version="1.0" encoding="utf-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://zeynalov.it-academy/xml/CoffeeHouses"
        xmlns:tns="http://zeynalov.it-academy/xml/CoffeeHouses"
        elementFormDefault="qualified">
    <element name="CoffeeHouses">
        <complexType>
            <sequence>
                <element name="CoffeHouse"
                         type="tns:CoffeeHouse"
                         maxOccurs="unbounded">
                </element>
            </sequence>
        </complexType>
    </element>
    <complexType name="CoffeeHouse">
        <sequence>
            <element name="Administrator" type="string"/>
            <element name="Waitress" type="string"/>
            <element name="Barista" type="string"/>
            <element name="Menus" type="tns:Menus"/>
        </sequence>
    </complexType>
    <complexType name="Menus">
        <sequence>
            <element name="Menu" type="tns:Menu"
                     minOccurs="1"
                     maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    <complexType name="Menu">
        <all>
            <element name="Description" type="string"/>
            <element name="Latte" type="string"/>
            <element name="Americano" type="string"/>
            <element name="Cappuccino" type="string"/>
            <element name="Espresso" type="string"/>
        </all>
    </complexType>
</schema>

=== GitTooth/JD2017-02-20/src/by/it/zeynalov/jd02_09/CoffeeHouses+XSD.xml
<?xml version="1.0" encoding="utf-8" ?>
<CoffeeHouses xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://zeynalov.it-academy/xml/CoffeeHouses CoffeeHouse.xsd"
         xmlns="http://zeynalov.it-academy/xml/CoffeeHouses">
   <CoffeHouse>
       <Administrator>Sam</Administrator>
       <Waitress>Kira</Waitress>
       <Barista>Din</Barista>
       <Menus>
               <Menu>
                   <Description>Menu</Description>
                   <Latte>Latte</Latte>
                   <Americano>Americano</Americano>
                   <Cappuccino>Cappucino</Cappuccino>
                   <Espresso>Espresso</Espresso>
               </Menu>
       </Menus>
   </CoffeHouse>
</CoffeeHouses>
