=== GitTooth/JD2017-02-20/src/by/it/radivonik/jd02_07/persons.dtd
<!ELEMENT Persons (Person)+>
<!ELEMENT Person (Email, Nickname, Password, Ads)>
<!ATTLIST Person id>
<!ATTLIST Person name>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT Nickname (#PCDATA)>
<!ELEMENT Password (#PCDATA)>
<!ELEMENT Ads (Ad)+>
<!ELEMENT Ad (Description, Adres, Floor, Floors, Square)>
<!ELEMENT Description (#PCDATA)>
<!ELEMENT Adres (#PCDATA)>
<!ELEMENT Floor (#PCDATA)>
<!ELEMENT Floors (#PCDATA)>
<!ELEMENT Square (#PCDATA)>

=== GitTooth/JD2017-02-20/src/by/it/radivonik/jd02_07/persons+DTD.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Persons SYSTEM "persons.dtd">
<Persons>
    <Person id="1" name="Alex">
        <Email>aa@tu.by</Email>
        <Nickname>aa</Nickname>
        <Password>aa</Password>
        <Ads>
            <Ad>
                <Description>
                    Хорошая квартира
                </Description>
                <Adres>
                    г.Минск
                </Adres>
                <Floor>3</Floor>
                <Floors>5</Floors>
                <Square>48.6</Square>
            </Ad>
            <Ad>
                <Description>
                    Квартира
                </Description>
                <Adres>
                    г.Минск
                </Adres>
                <Floor>3</Floor>
                <Floors>5</Floors>
                <Square>48.6</Square>
            </Ad>
        </Ads>
    </Person>
</Persons>
