=== GitTooth/JD2017-02-20/src/by/it/radivonik/jd02_07/persons.xsd
<?xml version="1.0" encoding="utf-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:tns="http://radivonik.it-academy/xml/persons"
        targetNamespace="http://radivonik.it-academy/xml/persons"
        elementFormDefault="qualified"
        attributeFormDefault="unqualified">
<element name="Persons">
    <complexType>
        <sequence>
            <element name="Person" type="tns:Person" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
</element>
<complexType name="Person">
    <sequence maxOccurs="1">
        <element name="Email" type="string"/>
        <element name="Nickname" type="string"/>
        <element name="Password" type="string"/>
        <element name="Ads" type="tns:Ads"/>
    </sequence>
    <attribute name="id"/>
    <attribute name="name"/>
</complexType>
<complexType name="Ads">
    <sequence maxOccurs="unbounded">
        <element name="Ad" type="tns:Ad"/>
    </sequence>
</complexType>
<complexType name="Ad">
    <sequence maxOccurs="1">
        <element name="Description" type="string"/>
        <element name="Adres" type="string"/>
        <element name="Floor" type="int"/>
        <element name="Floors" type="int"/>
        <element name="Square" type="decimal"/>
    </sequence>
</complexType>
</schema>

=== GitTooth/JD2017-02-20/src/by/it/radivonik/jd02_07/persons.xml
<?xml version="1.0" encoding="utf-8" ?>
<Persons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://radivonik.it-academy/xml/Persons persons.xsd"
xmlns="http://radivonik.it-academy/xml/Persons">
    <Person id="1" name="Alex" >
        <Email>aa@tu.by</Email>
        <Nickname>aa</Nickname>
        <Password>aa</Password>
        <Ads>
            <Ad>
                <Description>
                    Хорошая квартира
                </Description>
                <Adres>
                    г.Минск
                </Adres>
                <Floor>3</Floor>
                <Floors>5</Floors>
                <Square>48.6</Square>
            </Ad>
            <Ad>
                <Description>
                    Квартира
                </Description>
                <Adres>
                    г.Минск
                </Adres>
                <Floor>3</Floor>
                <Floors>5</Floors>
                <Square>48.6</Square>
            </Ad>
        </Ads>
    </Person>
</Persons>
