=== GitTooth/JD2017-02-20/src/by/it/psmishenko/jd02_7/Reader.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://psmishenko/xml/Readers"
        xmlns:tns="http://psmishenko/xml/Readers"
        elementFormDefault="qualified">
    <element name="Readers">
        <complexType>
            <sequence>
                <element name="Reader" type="tns:Reader" maxOccurs="unbounded"></element>
            </sequence>
        </complexType>
    </element>
    <complexType name="Reader">
        <sequence>
            <element name="Name" type="string"/>
            <element name="ID" type="positiveInteger"/>
            <element name="Age" type="positiveInteger"/>
            <element name="Books" type="tns:Books"/>
        </sequence>
    </complexType>
    <complexType name="Books">
        <sequence>
            <element name="Book" type="tns:Book" minOccurs="1" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    <complexType name="Book">
        <all> <!--в любом порядке -->
            <element name="Author" type="string"/>
            <element name="Title" type="string"/>
            <element name="Year" type="positiveInteger"/>
            <element name="ISBN" type="string"/>
            <element name="LID" type="positiveInteger"/>
        </all>
    </complexType>


</schema>

=== GitTooth/JD2017-02-20/src/by/it/psmishenko/jd02_7/Readers+XSD.xml
<?xml version="1.0" encoding="utf-8" ?>
<Readers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation = "http://psmishenko/xml/Readers Reader.xsd"
xmlns="http://psmishenko/xml/Readers">  <!--читатель в библиотеке -->
    <Reader>
        <Name>Vasya</Name>  <!--Имя читателя -->
        <ID>14322</ID>       <!--Уникальный номер читателя в библиотеке (номер уч. записи и т.п.) -->
        <Age>88</Age>
        <Books>             <!--Книги "на руках" -->
            <Book>
                <Author>Stephen King</Author>
                <Title>The Dead Zone</Title>
                <Year>1979</Year>
                <ISBN>978-0-670-26077-5</ISBN>   <!-- International Standard Book Number -->
                <LID>331177</LID>  <!-- Номер книги в библиотеке -->
            </Book>
            <Book>
                <Author>Arthur Conan Doyle</Author>
                <Title>Cremona</Title>
                <Year>1898</Year>
                <ISBN>928-0-610-21177-5</ISBN>   <!-- International Standard Book Number -->
                <LID>22112</LID>  <!-- Номер книги в библиотеке -->
            </Book>
        </Books>
    </Reader>
</Readers>
