=== GitTooth/JD2017-02-20/src/by/it/korzun/jd02_07/Brigade.dtd
<!ELEMENT Brigades (Brigade)+>
<!ELEMENT Brigade (Pilots, Navigator, Radio-operator, Stewardess)>
<!ELEMENT Pilots (Pilot)+>
<!ELEMENT Pilot (#PCDATA)+>
<!ELEMENT Navigator (#PCDATA)>
<!ELEMENT Radio-operator (#PCDATA)>
<!ELEMENT Stewardess (#PCDATA)>

=== GitTooth/JD2017-02-20/src/by/it/korzun/jd02_07/Brigades+DTD.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Brigades SYSTEM "Brigade.dtd">
<Brigades>
    <Brigade>
        <Pilots>
            <Pilot>Ivan Ivanovich</Pilot>
            <Pilot>Walter Ritz</Pilot>
        </Pilots>
        <Navigator>Carolus Rex</Navigator>
        <Radio-operator>Gunter Jonas</Radio-operator>
        <Stewardess>Maria Ivanovna</Stewardess>
    </Brigade>
</Brigades>
