=== GitTooth/JD2017-02-20/src/by/it/kolenda/jd02_07/Clients.xsd
<?xml version="1.0" encoding="utf-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
        targetNamespace="http://kolenda"
        xmlns:tns="http://kolenda"
        elementFormDefault="qualified"
        <element name="Clients">
            <complexType>
                <all>
                    <element name="ClientFL">

                    </element>
                </all>
            </complexType>
        </element>

    <element name="ClientFL">
        <complexType>
            <all>
                <element name="PersonalData">
                    <sequence>
                        <element name="Name" type="string"/>
                        <element name="Profession" type="string"/>
                        <element name="Address" type="string"/>
                        <element name="Email" type="string"/>
                    </sequence>
                </element>
                <element name="AcctType">
                    <all>
                        <element name="Current" type="positiveInteger"/>
                        <element name="Depo" type="positiveInteger"/>
                        <element name="Credit" type="positiveInteger"/>
                    </all>
                </element>
                <element name="Actions">
                    <sequence>
                        <element name="Pay" type="positiveInteger"/>
                        <element name="Refill" type="positiveInteger"/>
                        <element name="Withdraw" type="positiveInteger"/>
                        <element name="block" type="boolean"/>
                    </sequence>
                </element>
            </all>
        </complexType>
    </element>
</schema>

=== GitTooth/JD2017-02-20/src/by/it/kolenda/jd02_07/Clients.xml
<?xml version="1.0" encoding="utf-8" ?>

<Clients xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://kolenda clients.xsd"
    xmlns="http://kolenda">
    <Fiz_lico>
        <Name>Иванов Иван Иванович</Name>
        <Profession>Инжинер</Profession>
        <Address>г.Минск, ул.Гая, д.15, кв.1</Address>
        <AcctType>
            <Depo>true</Depo>
            <Credit>false</Credit>
            <Current>false</Current>
        </AcctType>
    </Fiz_lico>
    <Yur_lico>
        <Name>ООО Рога и Копыта</Name>
        <Industry>Здравоохранение</Industry>
        <Address>г.Минск, ул.Нестерова, д.1, кв.100</Address>
        <AcctType>
            <Depo>true</Depo>
            <Credit>true</Credit>
            <Current>true</Current>
        </AcctType>
    </Yur_lico>
</Clients>
