=== GitTooth/JD2017-02-20/src/by/it/kolenda/jd02_07/Clients.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT Clients (ClientFL)+>
        <!ELEMENT ClientFL (PersonalData,AcctType,Actions)>
        <!ELEMENT PersonalData (Name,Profession,Address,Email)>
        <!ELEMENT Name (#PCDATA)>
        <!ELEMENT Profession (#PCDATA)>
        <!ELEMENT Address (#PCDATA)>
        <!ELEMENT Email (#PCDATA)>
        <!ELEMENT AcctType (Current,Depo,Credit)>
        <!ELEMENT Current (#PCDATA)>
        <!ELEMENT Depo (#PCDATA)>
        <!ELEMENT Credit (#PCDATA)>
        <!ELEMENT Actions (Pay,Refill,Withdraw,Block)>
        <!ELEMENT Pay (#PCDATA)>
        <!ELEMENT Refill (#PCDATA)>
        <!ELEMENT Withdraw (#PCDATA)>
        <!ELEMENT Block (#PCDATA)>

=== GitTooth/JD2017-02-20/src/by/it/kolenda/jd02_07/Clients+DTD.xml
<?xml version="1.0" encoding="utf-8"?>
        <!DOCTYPE Clients SYSTEM "Clients.dtd">
<Clients>
    <Fiz_lico>
        <Name>Иванов Иван Иванович</Name>
        <Profession>Инжинер</Profession>
        <Address>г.Минск, ул.Гая, д.15, кв.1</Address>
        <AcctType>
            <Depo>true</Depo>
            <Credit>false</Credit>
            <Current>true</Current>
        </AcctType>
    </Fiz_lico>
    <Yur_lico>
        <Name>ООО Рога и Копыта</Name>
        <Industry>Здравоохранение</Industry>
        <Address>г.Минск, ул.Нестерова, д.1, кв.100</Address>
        <AcctType>
            <Depo>true</Depo>
            <Credit>true</Credit>
            <Current>true</Current>
        </AcctType>
    </Yur_lico>
</Clients>
